<?php
class Backup extends CI_Controller{
	function __construct(){
		parent::__construct();
		$this->load->model(array('fb'));
	}
	function backup_fbs(){
		$fbs = new Fb();
		$fbs->get();
		$text = '';
		foreach ($fbs as $fb){
			$text.='insert into fbs (';
			$text.='id,';
			$text.='branch_id,';
			$text.='category_id,';
			$text.='service_id,';
			$text.='client_id,';
			$text.='lainnya,';
			$text.= 'phone_area varchar(5), ';
			$text.= 'applicant varchar(200), ';
			$text.= 'applicant_religion_id smallint, ';
			$text.= 'applicant_position_id smallint, ';
			$text.= 'no_fb varchar(20), ';
			$text.= 'fb_date date, ';
			$text.= 'no_id varchar(150), ';
			$text.= 'phone_area_pemohon varchar(5), ';
			$text.= 'telp_hp varchar(50), ';
			$text.= 'hp varchar(13), ';
			$text.= 'hp2 varchar(13), ';
			$text.= 'email varchar(150), ';
			$text.= 'setup_fee double, ';
			$text.= 'setup_fee_cur varchar(1), ';
			$text.= 'monthly_subscription_fee double, ';
			$text.= 'monthly_subscription_fee_cur varchar(1), ';
			$text.= 'device_fee double, ';
			$text.= 'device_fee_cur varchar(1), ';
			$text.= 'other_fee double, ';
			$text.= 'other_fee_cur varchar(1), ';
			$text.= 'service_information tinytext, ';
			$text.= 'activation_date date, ';
			$text.= 'subscription_periode date, ';
			$text.= 'subscription_periode2 date, ';
			$text.= 'special_request tinytext, ';
			$text.= 'sale_id int, ';
			$text.= 'status_id enum(\'0\',\'1\',\'2\') default \'1\', ';
			$text.= 'tanggal timestamp, ';
			$text.= 'kode_pelanggan varchar(30), ';
			$text.= 'state_id int default 1, ';
			$text.= 'security_deposit double, ';
			$text.= 'security_deposit_cur varchar(1), ';
			$text.= 'security_deposit_ppn varchar(1), ';
			$text.= 'security_deposit2 decimal(15,2), ';
			$text.= 'security_deposit2_cur varchar(1), ';
			$text.= 'setup_fee_ppn varchar(1) default "n", ';
			$text.= 'monthly_subscription_fee_ppn varchar(1) default "n", ';
			$text.= 'device_fee_ppn varchar(1) default "n", ';
			$text.= 'other_fee_ppn varchar(1) default "n", ';
			$text.= 'faktur_pajak varchar(1) default "n", ';
			$text.= 'setup_fee_pph varchar(1) default "n", ';
			$text.= 'material_fee decimal(15,2), ';
			$text.= 'material_fee_cur varchar(1), ';
			$text.= 'material_fee_ppn varchar(1), ';
			$text.= 'material_fee_pph varchar(1), ';
			$text.= 'subscription_freqwency_id int, ';
			$text.= 'maintenance_freqwency_id int, ';
			$text.= 'payment_freqwency_id smallint, ';
			$text.= 'device_date date, ';
			$text.= 'device_warranty varchar(1), ';
			$text.= 'server_location varchar(1), ';
			$text.= 'domainperiode1 date, ';
			$text.= 'domainperiode2 date, ';
			$text.= 'hostingperiode1 date, ';
			$text.= 'hostingperiode2 date, ';
			$text.= 'hosting_package_id smallint, ';
			$text.= 'domainname varchar(20), ';
			$text.= 'maintenance_fee decimal(15,2), ';
			$text.= 'maintenance_fee_cur varchar(1), ';
			$text.= 'maintenanceperiode1 date, ';
			$text.= 'maintenanceperiode2 date, ';
			$text.= 'projectdp_fee decimal(15,2), ';
			$text.= 'projectdp_fee_ppn varchar(1), ';
			$text.= 'projectdp_fee_pph varchar(1), ';
			$text.= 'projectdp_fee_cur varchar(1), ';
			$text.= 'projecttermin1_fee decimal(15,2), ';
			$text.= 'projecttermin1_fee_ppn varchar(1), ';
			$text.= 'projecttermin1_fee_pph varchar(1), ';
			$text.= 'projecttermin1_fee_cur varchar(1), ';
			$text.= 'projecttermin2_fee decimal(15,2), ';
			$text.= 'projecttermin2_fee_ppn varchar(1), ';
			$text.= 'projecttermin2_fee_pph varchar(1), ';
			$text.= 'projecttermin2_fee_cur varchar(1), ';
			$text.= 'projecttermin3_fee decimal(15,2), ';
			$text.= 'projecttermin3_fee_ppn varchar(1), ';
			$text.= 'projecttermin3_fee_pph varchar(1), ';
			$text.= 'projecttermin3_fee_cur varchar(1), ';
			$text.= 'projecttermin4_fee decimal(15,2), ';
			$text.= 'projecttermin4_fee_ppn varchar(1), ';
			$text.= 'projecttermin4_fee_pph varchar(1), ';
			$text.= 'projecttermin4_fee_cur varchar(1), ';
			$text.= 'project_faktur_pajak varchar(1), ';
			$text .='projecttermin1_jt date, ';
			$text .='projecttermin2_jt date, ';
			$text .='projecttermin3_jt date, ';
			$text .='projecttermin4_jt date, ';
			$text .='webappdp_fee decimal(15,2), ';
			$text .='webappdp_fee_cur varchar(1), ';
			$text .='webappdp_fee_pph varchar(1), ';
			$text .='webappdp_fee_ppn varchar(1), ';
			$text .='webapptermin1_fee decimal(15,2), ';
			$text .='webapptermin1_fee_ppn varchar(1), ';
			$text .='webapptermin1_fee_pph varchar(1), ';
			$text .='webapptermin1_fee_cur varchar(1), ';
			$text .='webapptermin2_fee decimal(15,2), ';
			$text .='webapptermin2_fee_ppn varchar(1), ';
			$text .='webapptermin2_fee_pph varchar(1), ';
			$text .='webapptermin2_fee_cur varchar(1), ';
			$text .='webapptermin3_fee decimal(15,2), ';
			$text .='webapptermin3_fee_ppn varchar(1), ';
			$text .='webapptermin3_fee_pph varchar(1), ';
			$text .='webapptermin3_fee_cur varchar(1), ';
			$text .='webapptermin4_fee decimal(15,2), ';
			$text .='webapptermin4_fee_ppn varchar(1), ';
			$text .='webapptermin4_fee_pph varchar(1), ';
			$text .='webapptermin4_fee_cur varchar(1), ';
			$text .='webapp_faktur_pajak varchar(1),';
			$text .='note text, ';
			$text .='fax_kode_area varchar(5)) ';
			
			
			$text.=') values (' . $fb->id . ')';
		}
	}
}